apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  keys: |
    worker_processes 2;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile      on;
        keepalive_timeout  65;
        # For long domain names (e.g. AWS hosts)
        server_names_hash_bucket_size 128;
        include /etc/nginx/conf.d/*.conf;
        client_max_body_size 0;
    }
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-template-config-map
data:
  keys: |
        server {
            listen       80;
            server_name  _ default;
            return       404;
        }
        server {
            listen       80;
            server_name  ${CVAT_HOST};
            proxy_pass_header       X-CSRFToken;
            proxy_set_header        Host $http_host;
            proxy_pass_header       Set-Cookie;
            location ~* /api/.*|git/.*|opencv/.*|analytics/.*|static/.*|admin(?:/(.*))?.*|documentation/.*|django-rq(?:/(.*))? {
                proxy_pass              http://cvat:8080;
            }
            location / {
                proxy_pass              http://cvat_ui;
            }
        }
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cvat-proxy
  template:
    metadata:
      labels:
        app: cvat-proxy
    spec:
      volumes:
        - name: nginx-configmap-volume
          configMap:
            name: nginx-config-map
        - name: nginx-template-configmap-volume
          configMap:
            name: nginx-template-config-map
      containers:
        - env:
            - name: CVAT_HOST
              value: localhost
          name: container-configmap
          image: 'nginx:stable-alpine'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-configmap-volume
              mountPath: /etc/nginx/
            - name: nginx-template-configmap-volume
              mountPath: /etc/nginx/conf.d/
      restartPolicy: Always
     
            
            

    
        
      

