apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-proxy
  name: cvat-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: cvat-proxy
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - envsubst '$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf
          && nginx -g 'daemon off;'
        env:
        - name: CVAT_HOST
          value: localhost
        image: nginx:stable-alpine
        imagePullPolicy: ""
        name: cvat-proxy
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
