apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: cvat-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: cvat
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_USER
          value: root
        image: postgres:10-alpine
        imagePullPolicy: ""
        name: cvat-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: cvat-db
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cvat-db
        persistentVolumeClaim:
          claimName: cvat-db
status: {}
