apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-ui
  name: cvat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: cvat-ui
    spec:
      containers:
      - image: openvino/cvat_ui
        imagePullPolicy: ""
        name: cvat-ui
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
