apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
spec:
  ports:
  - name: "6543"
    port: 6543
    targetPort: 5432
  selector:
    io.kompose.service: cvat-db
status:
  loadBalancer: {}
