apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat
  name: cvat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cvat
    spec:
      containers:
      - env:
        - name: ALLOWED_HOSTS
          value: '*'
        - name: CVAT_POSTGRES_HOST
          value: cvat_db
        - name: CVAT_REDIS_HOST
          value: cvat_redis
        - name: DJANGO_MODWSGI_EXTRA_ARGS
        image: openvino/cvat_server
        imagePullPolicy: ""
        name: cvat
        resources: {}
        volumeMounts:
        - mountPath: /home/django/data
          name: cvat-data
        - mountPath: /home/django/keys
          name: cvat-keys
        - mountPath: /home/django/logs
          name: cvat-logs
        - mountPath: /home/django/models
          name: cvat-models
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cvat-data
        persistentVolumeClaim:
          claimName: cvat-data
      - name: cvat-keys
        persistentVolumeClaim:
          claimName: cvat-keys
      - name: cvat-logs
        persistentVolumeClaim:
          claimName: cvat-logs
      - name: cvat-models
        persistentVolumeClaim:
          claimName: cvat-models
status: {}
